---
title: "Project 06: Hierarchical Clustering"
author: "Zoe Chow, Michael Bambha, Jacqueline Caldwell"
date: "`r format(Sys.time(), '%Y%m%d')`"
output:
  github_document:
    html_preview: false
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}



knitr::opts_chunk$set(echo=TRUE)
library('reticulate')
reticulate::conda_install(envname = "r-reticulate",
                        packages=c("dendropy", "biopython",
                                   "matplotlib"),
                        channel=c("bioconda", "conda-forge"), 
                        conda="auto")
```

------------------------------------------------------------------------

## Learning Objectives

1.  Implement a distance-based phylogeny neighbor joining algorithm
2.  Understanding of hierarchical clustering
3.  Manipulation of arrays and lists in Python

------------------------------------------------------------------------

## Imports

You will need to install a package called `ete3` for this project. You can do this by the command `conda install ete3`.

```{python}
from typing import List, Tuple, Dict
import numpy as np
from my_read_fasta import read_fasta
from smith_waterman import smith_waterman_max_score
```

------------------------------------------------------------------------

## Background

Today we will implement a distance-based phylogenetic tree construction method using the Neighbor-Joining (NJ) algorithm and Smith-Waterman local alignment scores. Unlike UPGMA (Unweighted Pair Group Method using Arithmetic averages), NJ produces unrooted trees and does not assume a constant evolutionary rate across lineages, making it more biologically realistic for analyzing sequence relationships.

We will use HIV-1 reverse transcriptase sequences to construct our phylogenetic tree. The Smith-Waterman algorithm will be used to generate pairwise local alignment scores, which will then be converted into distances for tree construction. This approach is particularly suitable for HIV sequence analysis as it: 1. Handles sequence variations effectively through local alignment 2. Accounts for potential rate heterogeneity across different viral strains 3. Does not assume a molecular clock

The ultimate output will be an unrooted phylogenetic tree representing the evolutionary relationships between the HIV-1 sequences, visualized using the ete3 library. This method provides insights into viral diversity and evolutionary patterns while avoiding the assumptions of simpler hierarchical clustering approaches.

The key innovations of this implementation are: - Use of Smith-Waterman for sensitive local alignment scoring - Implementation of Neighbor-Joining for unrooted tree construction - More biologically realistic evolutionary model

## Neighbor-Joining Algorithm

**Input**: Distance matrix $D$ for $n$ sequences

**Initialization**:
- Let $n$ be the number of sequences
- Assign each sequence $i$ to its own leaf node
- Initialize tree $T$ with leaf nodes
     empty graph with list of leaves 

**Iteration**:
While $n > 2$:
1. Calculate Q-matrix (centrality of the calculated distances) where:
   $Q(i,j) = (n-2)d(i,j) - \sum_{k=1}^n d(i,k) - \sum_{k=1}^n d(j,k)$

2.  Find pair $(i,j)$ with minimum $Q(i,j)$

3.  Calculate branch lengths: $d_i = \frac{d(i,j) + (r_i - r_j)/(n-2)}{2}$ $d_j = d(i,j) - d_i$ where $r_i = \sum_{k=1}^n d(i,k)$

4. Create new node $k$ INTERNAL NODE (ancestor)
   - Add branches from $k$ to $i$ and $j$ with lengths $d_i$ and $d_j$

    -   Add branches from $k$ to $i$ and $j$ with lengths $d_i$ and $d_j$

5.  Update distances to remaining nodes $x$: $d(k,x) = \frac{d(i,x) + d(j,x) - d(i,j)}{2}$

6.  Remove nodes $i$ and $j$

<End Marcus Stuff>
---
<Jacque started here>
## Pseudo Code:

I have taken Marcus' above "plan" and started to flesh it out a bit more 

Data Structure discussion:

sequences = list of 'n' Dictionaries (name seq) #from fasta file

Dmatrix = n x n numpy array of normalized distances between the sequences.
D is the Dmatrix (distance matrix) n x n [ixj] where i and j are sequences
    Calculated from smith-waterman "score" going from one sequence i to sequence j
Distance from S(i) to S(j) = D(i,j)
If k is an internal node on our graph:
  Distance from S(k,j) (aka S(j,k)) = D(i,j) - D(i,k) 
  
 T:
    will need n leaves (a node with only one edge to rest of graph)
    will need internal_nodes a node that has more than 1 edge
    will need edges associated with all nodes 
    edges have lengths
    
    Tree:
    class TreeNode
      name = from sequences[].name 
      children: List of nodes
      edges:  list of Edges?
    
     class Edge 
      length: int # this gets recalculated every time.
    
    will need methods to create_leaves, merge_nodes, prune 

  Q is the Qmatrix n x n  numpy array.
  taking/measuring how central the cluster is; (penalizes outliers)
    where Q[i,j] = eqn1 (see above)
  
Other things to know:
  # note:  D(k,j) = D(j,k) for all values of j and k; symetry.
  # also: There will always be a distance from i to j; though they may not be directly connected.
  # also:  D(k,k) = 0 for all values of k.
  # also:  nodes will have an idea of 'degrees' as well as to which other nodes they are connected, and which may be good if something is leaf... 
  # also:  merge nodes -- we will know who the common ancestor is 
    
**Input** (begin pseudo code)

Fasta file has been imported, and returns sequences a list of Dictionarys 
                with name as key, seq as value

  # note: n = 20 as their are 20 seq in our fasta file. 
  
  Next step will be:

Initialize the Distance Matrix:

Micheal has used his Smith-Waterman code as well as creating a normalization process.
  Dmatrix is created.
  
To decrease the insanity of the next section, I have pulled out the equations....

eqn1 = $Q(i,j) = (n-2)d(i,j) - \sum_{k=1}^n d(i,k) - \sum_{k=1}^n d(j,k)$
eqn2 = Branch_length =  $d_i = \frac{d(i,j) + (r_i - r_j)/(n-2)}{2}$
   $d_j = d(i,j) - d_i$
   where $r_i = \sum_{k=1}^n d(i,k)$
eqn3 = $d(k,x) = \frac{d(i,x) + d(j,x) - d(i,j)}{2}$

**Input** \## While working with Nikaela (project 4), I implemented a read_fasta that was a hacked up ##version of Marcus's read fasta from project 3. \## \## I will put that file in our project06 directory as my_read_fasta.py \## feel free to mess with it, make it more error tolerant, etc, as I haven't checked ##. for errors on openning or ??? ##.I am adding my_read_fasta.py and the appropriate import

  for t in set from 0 to n
    T.leaf = create_leaf( S[name] ); tuple from dictionary associated with name
  
    
**Iteration**: 
q = n (number of sequences)

While q > 2:
1. Calculate Q-matrix where:
  for i in ... do
    for j in ... do
      Q[i,j] = "eqn1" (given S(i) and S(j))

2. Find pair (i,j) with minimum Q(i,j) -- 
Note that we need to be aware that the diagonal are 0s and we only need to look 
at half the array 
  find S(i) and S(j) that represent the entry in Q

3. Calculate branch lengths:    
  Now that we have i and j; 

  from "eqn2" given S(i), S(j):
  
  calculate ?2? branch lengths ( this is distance from i to j );

4. Create new node k
     "Add branches from k to i and j with branch lengths D(i) and D(j)"

5. Update distances to remaining nodes:
   using eqn3 above, re-calculate Dmatrix????

6. Remove nodes i and j from active nodes list
  we have now connected them with node k, and their edges have lengths.
 (should this happen before item 5?) ?remove column i and column j ; row i and row j

7. Add internal node k to active nodes list

8. q = q - 1

**Termination**:
When q = 2 with remaining nodes i and j:     # last node to add
- Add final branch between i and j with length d(i,j)
- Return unrooted tree T
<end area for pseudo code>

## Distance metrics for comparing sequences

### Smith-Waterman

This was previously implemented. Feel free to import if you know how...or Copy & Paste.

```{python}
class Node:
    def __init__(self, name, left=None, right=None, dist_left=None, dist_right=None):
        self.name = name
        self.left = left
        self.right = right
        self.dist_left = dist_left
        self.dist_right = dist_right

    def is_leaf(self):
        return self.left is None and self.right is None

    def to_newick(self):
        pass
```

```{python}
def build_similarity_matrix(sequences: Dict[str, str]) -> Tuple[np.ndarray, List[str]]:
    """Builds distance matrix using Smith-Waterman scores.

    Args:
        sequences (Dict[str, str]): Dictionary of HIV RT sequences

    Returns:
        Tuple[np.ndarray, List[str]]: Distance matrix and list of sequence IDs

    Examples:
        >>> seqs = read_fasta("lafayette_SARS_RT.fasta")
        >>> mat, ids = build_distance_matrix(seqs)
        >>> mat[0:3, 0:3]  # Show 3x3 slice of distance matrix
        array([[0.000, 0.004, 0.012],
              [0.004, 0.000, 0.012],
              [0.012, 0.012, 0.000]])
        >>> len(ids)  # Number of sequences
        19
    """
    n_seq = len(sequences)
    seq_ids = list(sequences.keys())
    seqs = list(sequences.values())
    dm = np.zeros((n_seq, n_seq))
    for i in range(n_seq):
        for j in range(i, n_seq):
            dm[i, j] = smith_waterman_max_score(seqs[i], seqs[j])
            dm [j, i] = dm[i, j]
    return dm


def normalize_similarity_matrix(similarity_matrix: np.ndarray) -> np.ndarray:
    """Normalize Smith-Waterman scores using a cosine-similarity approach -
    divide scores by the square root of the maximum possible alignment score.
    This is because with variable length sequences, longer sequences are biased
    as they are more likely to have higher raw scores, even if alignment is
    poorer.

    Args:
        similarity_matrix (np.ndarray): Matrix of raw Smith-Waterman scores

    Returns:
        np.ndarray: Matrix of normalized Smith-Waterman scores based on
        square root of maximum possible score.
    """
    return similarity_matrix / np.sqrt(np.outer(np.diag(similarity_matrix), np.diag(similarity_matrix))), seq_ids
    

def build_distance_matrix(sequences: Dict[str, str]) -> Tuple[np.ndarray, List[str]]:
    """Builds distance matrix using Smith-Waterman scores.

    Args:
        sequences (Dict[str, str]): Dictionary of HIV RT sequences

    Returns:
        Tuple[np.ndarray, List[str]]: Distance matrix and list of sequence IDs

    Examples:
        >>> seqs = read_fasta("lafayette_SARS_RT.fasta")
        >>> mat, ids = build_distance_matrix(seqs)
        >>> mat[0:3, 0:3]  # Show 3x3 slice of distance matrix
        array([[0.000, 0.004, 0.012],
              [0.004, 0.000, 0.012],
              [0.012, 0.012, 0.000]])
        >>> len(ids)  # Number of sequences
        19
    """
    sequence_ids = list(sequences.keys())
    similarity_matrix = build_similarity_matrix(sequences)[0]
    normalized_sm = normalize_similarity_matrix(similarity_matrix)
    return (1 - normalized_sm, seq_ids), sequence_ids
```

```{python}
def build_q_matrix(distance_matrix: np.ndarray) -> np.ndarray:
    """Build a q-matrix from distance matrix.

    Args:
        distance_matrix (np.ndarray): Normalized distance matrix

    Returns:
        np.ndarray: Q-matrix from normalized distance scores
    """
    n_taxa = distance_matrix.shape[0]
    # because dm is symmetric, r_i = r_j
    r_i = np.sum(distance_matrix, axis=1)
    # np.sum returns a vector of shape (n_taxa,)
    # to broadcast, we need to reshape to (1, n) and (n, 1)
    qm = (n_taxa - 2) * distance_matrix - r_i[:, None] - r_i[None, :]
    np.fill_diagonal(qm, np.inf) # diagonal is meaningless algorithmically
    return qm
```

```{python}
def get_min_distance(matrix):
    ''' Function to find the smallest value off-diagonal in the distance
    matrix provided. This is used in the UPGMA algorithm.

    Since we fill the diagonal in the q-matrix with np.inf, we will
    assume that we don't need to explicitly handle ignoring the diagonal.
    
    Args: 
        matrix (2D numpy array): a distance matrix

    Returns:
        min (float): The smallest distance in the matrix
        pos (tuple): The x and y position of the smallest distance
    
    '''
    return np.min(matrix), np.unravel_index((np.argmin(matrix)), shape=matrix.shape)
```

```{python}
def calculate_branch_lengths(distance_matrix: np.ndarray, i: int, j: int) -> Tuple[float, float]:
    """Calculate the branch lengths for a given distance
    matrix and i, j

    Args:
        distance_matrix (np.ndarray): Matrix of normalized distances
        i (int): index corresponding to species i
        j (int): index corresponding to species j

    Returns:
        Tuple[float, float]: Branch lengths of i and j, respectively.
    """
    n_taxa = distance_matrix.shape[0]
    r_i = np.sum(distance_matrix[i, :])
    r_j = np.sum(distance_matrix[j, :])
    d_ij = distance_matrix[i, j]
    
    L_i = 0.5 * d_ij + (r_i - r_j) / (2 * (n_taxa - 2))
    L_j = d_ij - L_i

    return L_i, L_j
```

```{python}
def calculate_k_distances(distance_matrix: np.ndarray, i: int, j: int) -> np.ndarray:
    """Find the distances of all other nodes to a newly merged node k=(i,j).

    Args:
        distance_matrix (np.ndarray): Distance matrix
        i (int): _description_
        j (int): _description_

    Returns:
        np.ndarray: np array of size 1xn-1, where n is the # of rows
        or columns of the square distance matrix as input.
    """
    mask = np.ones(distance_matrix.shape[0], dtype=bool)
    mask[[i, j]] = False
    new_distances = 0.5 * (distance_matrix[i, mask] + distance_matrix[j, mask] - distance_matrix[i, j])
    return new_distances
```

```{python}
def update_distance_matrix(distance_matrix: np.ndarray, i: int, j: int) -> np.ndarray:
    """Update a distance matrix to remove row/columns i, j and include a new node k.
    Update all of the distances to this new node k. 

    Args:
        distance_matrix (np.ndarray): Distance matrix to update
        i (int): index corresponding to species i
        j (int): index corresponding to species j 

    Returns:
        np.ndarray: Updated distance matrix with k
    """
    new_distances = calculate_k_distances(distance_matrix, i, j)
    distance_matrix = np.delete(distance_matrix, [i, j], axis=1)
    distance_matrix = np.delete(distance_matrix, [i, j], axis=0)
    distance_matrix = np.vstack((distance_matrix, new_distances))
    # since our temporary array is n+1, we can append 0, which is the diagonal.
    # hstack needs a reshaped array, else it interprets (n+1,) as (1,n+1).
    # below we reshape to a proper column vector so we can stack it
    distance_matrix = np.hstack((distance_matrix, np.append(new_distances, 0)[:, None]))
    return distance_matrix
```

```{python}
def neighbor_joining(
    distance_matrix: np.ndarray,
    labels: List[str]
) -> str:
    """Implements Neighbor-Joining algorithm for phylogenetic tree construction.

    Args:
        distance_matrix (np.ndarray): Distance matrix from Smith-Waterman scores
        labels (List[str]): Sequence identifiers

    Returns:
        str: Newick format tree string

    Examples:
        >>> seqs = read_fasta("lafayette_SARS_RT.fasta")
        >>> mat, ids = build_distance_matrix(seqs)
        >>> tree = neighbor_joining(mat, ids)
        >>> tree.startswith("((DM1:0.002,DM2:0.002)")  # Start of Newick string
        True
        >>> tree.count(",")  # Number of separators in tree
        18
    """
    seqs = read_fasta("lafayette_SARS_RT.fasta")
    distance_matrix, seq_ids = build_distance_matrix(seqs)
    n_taxa = distance_matrix.shape[0]
    while n_taxa > 2:
      q_matrix = build_q_matrix(distance_matrix)
      min_distance, min_coords = get_min_distance(q_matrix)

    
    
```

```{python}
#def plot_tree(newick_tree: str) -> None:
#    """Plots phylogenetic tree using ete3.
#   Args:
#        newick_tree (str): Tree in Newick format
#    """
#    tree = ete3.Tree(newick_tree)
#    ts = ete3.TreeStyle()
#    ts.show_leaf_name = True
#    ts.mode = "c"  # circular style
#    return tree.render("%%inline", tree_style=ts)
```


```{python}
import dendropy
from Bio import Phylo
import matplotlib.pyplot as plt
import io

# From a file
def plot_tree(newick_tree: str) -> None:
  '''Plots phylogenetic tree using Dendropy
  
  Args:
      newick_tree(str):  Tree in Newick format
  '''
# From a string
  tree = dendropy.Tree.get(data=newick_tree, schema="newick")
  tree.print_plot()

  # Other Newick string examples
  # newick_string = "((A:1.0,B:1.0):0.5,C:2.0);"
  # newick_string = "((A:1,B:1):1,C:2);"
  
# Create a sample Newick tree string or read from a file
# Example Newick string:
  newick_string = "(((A:0.1,B:0.2):0.3,(C:0.4,D:0.5):0.6):0.7,(E:0.8,F:0.9,G:1.0):1.1);"

# Parse the Newick string
  tree = Phylo.read(io.StringIO(newick_string), "newick") # Using io.StringIO for string input

# Display the tree as ASCII art
  Phylo.draw_ascii(tree)

# Draw the tree
  Phylo.draw(tree)

# Show the plot
  plt.show()

```

  
```{python}
if __name__ == "__main__":
    # Read HIV RT sequences
  sequences = read_fasta("lafayette_SARS_RT.fasta")
  print(f"Loaded lafayette_SARS_RT.fasta, total: {len(sequences)}")
    
  # Build distance matrix using Smith-Waterman
  dist_matrix, seq_ids = build_distance_matrix(sequences)
  print(f"Built distance matrix using S-W: {dist_matrix}")
    
  # Generate unrooted tree using Neighbor-Joining
  tree = neighbor_joining(dist_matrix, seq_ids)
    
  # Testing plot tree
  # tree = "((A:0.2, B:0.3):0.3,(C:0.5, D:0.3):0.2):0.3;"
  # Plot tree
  plot_tree(tree)
  
```

